apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama-server
  template:
    metadata:
      labels:
        app: ollama-server
    spec:
      containers:
      - name: ollama-server
        image: gcr.io/<your-gcp-project-id>/ollama-server
        ports:
        - containerPort: 9999
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "9999"
